export const GET_PRENDAPORID = "GET_PRENDAPORID ";
export const GET_PRENDAPORID_SUCCESS = "GET_PRENDAPORID_SUCCESS ";
export const GET_PRENDAPORID_FAILED = "GET_PRENDAPORID_FAILED ";

export const GET_PRENDAPORNOMBRE = "GET_PRENDAPORNOMBRE ";
export const GET_PRENDAPORNOMBRE_SUCCESS = "GET_PRENDAPORNOMBRE_SUCCESS ";
export const GET_PRENDAPORNOMBRE_FAILED = "GET_PRENDAPORNOMBRE_FAILED ";
